/**
 * Noms d'icônes.
 *
 * La liste vit dans le domaine, sans dépendance : les catalogues (catégories de dépense,
 * types d'entretien…) désignent leurs icônes par ces noms, et l'interface les dessine.
 * Un test de forme vérifie que chaque nom listé ici a bien un tracé dans le jeu d'icônes —
 * sans quoi un catalogue pourrait désigner une icône qui n'existe pas, et l'écran
 * afficherait un vide silencieux.
 */

export const ICON_NAMES = [
  'home',
  'car',
  'car-multiple',
  'key',
  'user',
  'users',
  'file-text',
  'file-check',
  'folder',
  'euro',
  'wallet',
  'banknote',
  'credit-card',
  'receipt',
  'chart-bar',
  'chart-line',
  'trending-up',
  'percent',
  'wrench',
  'gauge',
  'fuel',
  'tire',
  'battery',
  'droplet',
  'snowflake',
  'filter',
  'settings',
  'plus',
  'search',
  'calendar',
  'clock',
  'alert-triangle',
  'alert-circle',
  'check-circle',
  'x-circle',
  'chevron-right',
  'chevron-down',
  'chevron-left',
  'trash',
  'edit',
  'download',
  'upload',
  'share',
  'printer',
  'lock',
  'fingerprint',
  'archive',
  'camera',
  'image',
  'shield',
  'bell',
  'tag',
  'list',
  'clipboard',
  'signature',
  'rotate',
  'refresh',
  'map-pin',
  'sparkles',
  'truck',
  'shield-check',
  'file-spreadsheet',
] as const;

export type IconName = (typeof ICON_NAMES)[number];
